name: "NO_INTERVENTION"
env_parameters:
  random_village_location: 0
  agent_count: 3
no_graphics: True
intervention_type: "none"

lr: 0.005
lambda_: 0.95
gamma: 0.99
sgd_minibatch_size: 900
train_batch_size: 9000
num_sgd_iter: 3
clip_param: 0.2
