name: "AWS_LLM_HUMAN_LLAMA_3_8B_INSTRUCT_INTERVENTION" # WFS_auto_LLM_decay_DEBUG
env_parameters:
  training: 1
  human_intervention: 0
  task: 0
  ext_fire_reward: 1000
  prep_tree_reward: 0.1
  water_pickup_reward: 0.1
  fire_out_reward: 0
  crash_reward: -100
  fire_close_to_city_reward: 0
no_graphics: True
intervention_type: "llm" # "none", "auto", "llm", "human"
model: "llama-3-8b-instruct" # "llama-3.1-8b-instruct", Pharia-1-LLM-7B-control-aligned, "llama-3-8b-instruct"
shot: ["zero"]
lr: 0.005
lambda_: 0.95
gamma: 0.99
sgd_minibatch_size: 900
train_batch_size: 9000
num_sgd_iter: 3
clip_param: 0.2
