name: "NL_LLAMA_3.1"
env_parameters:
  random_village_location: 0
no_graphics: True
intervention_type: "llm"
model: "llama-3.1-8b-instruct"
shot: "few"

lr: 0.005
lambda_: 0.95
gamma: 0.99
sgd_minibatch_size: 900
train_batch_size: 9000
num_sgd_iter: 3
clip_param: 0.2
